/**
 * One actionable fix per check id, keyed to lib/analyzer.ts's CHECKS[].
 * Shown in the Score tab when a check isn't passing. Keep these short,
 * concrete, and framework-agnostic — the Open Graph and Twitter tabs already
 * have dedicated copy-paste HTML/Next.js snippets for their own tags.
 */
export const CHECK_FIXES: Record<string, string> = {
  "title-present": 'Add a <title> tag inside <head>, e.g. <title>Your page title</title>.',
  "title-length": "Rewrite the title to land between 15 and 60 characters — long enough to be descriptive, short enough to avoid truncation in search results.",
  "description-present": 'Add <meta name="description" content="..."> inside <head> with a one- to two-sentence summary of the page.',
  "description-length": "Aim for 120–160 characters — enough to be useful in a search snippet without getting cut off.",
  "canonical-present": 'Add <link rel="canonical" href="https://yoursite.com/this-page"> to tell crawlers which URL is the source of truth.',
  "favicon-present": 'Add <link rel="icon" href="/favicon.ico"> (or an SVG/PNG equivalent) so tabs and bookmarks show your icon.',
  "lang-present": 'Set the language on the root element: <html lang="en"> (swap "en" for your page\'s language).',
  "viewport-present": 'Add <meta name="viewport" content="width=device-width, initial-scale=1"> for correct mobile rendering.',
  "og-title": 'Add <meta property="og:title" content="Your title"> — shown by nearly every platform that renders link previews.',
  "og-description": 'Add <meta property="og:description" content="..."> so social platforms show a description instead of falling back to page text.',
  "og-image": 'Add <meta property="og:image" content="https://yoursite.com/preview.jpg"> — without it, most platforms show no image at all.',
  "og-url": 'Add <meta property="og:url" content="https://yoursite.com/this-page"> so shares consolidate to one canonical URL.',
  "og-type": 'Add <meta property="og:type" content="website"> (or "article", "product", etc. if more specific).',
  "og-site-name": 'Add <meta property="og:site_name" content="Your Site"> to brand previews with your site name.',
  "og-locale": 'Add <meta property="og:locale" content="en_US"> so platforms render region-appropriate formatting.',
  "og-image-dims": 'Add <meta property="og:image:width" content="1200"> and <meta property="og:image:height" content="630"> so platforms can reserve layout space before the image loads.',
  "twitter-card": 'Add <meta name="twitter:card" content="summary_large_image"> to control how the card renders on X.',
  "twitter-title": 'Add <meta name="twitter:title" content="..."> or rely on og:title as a fallback.',
  "twitter-description": 'Add <meta name="twitter:description" content="..."> or rely on og:description as a fallback.',
  "twitter-image": 'Add <meta name="twitter:image" content="..."> or rely on og:image as a fallback.',
  "twitter-site": 'Add <meta name="twitter:site" content="@yourhandle"> to attribute the card to your account.',
  "image-loads": "Double-check the og:image URL is publicly reachable (not behind auth, not blocked by robots) and returns a 200 status.",
  "image-size": "Compress the image — most platforms cap preview images around 5MB, and smaller files load faster in the preview itself.",
  "image-aspect-ratio": "Crop or re-export the image closer to a 1.91:1 ratio (e.g. 1200×630) so it isn't awkwardly cropped by platforms.",
  "image-min-size": "Re-export the image at least 600×315px — smaller images may be rejected or scaled up poorly.",
  https: "Move the site to HTTPS. Browsers and most platforms treat HTTP links as insecure and may refuse to preview them.",
  charset: 'Add <meta charset="utf-8"> as the first tag inside <head>.',
  "robots-not-blocking": 'Remove or relax the robots meta tag/header (avoid content="noindex" or "none") if you want this page indexed and shared.',
  "theme-color": 'Add <meta name="theme-color" content="#yourcolor"> — used by Discord and mobile browser chrome.',
  "no-redirect-chain": "Point your canonical/og:url tags — and any inbound links — directly at the final destination URL to skip the redirect hop.",
  "response-time": "Investigate server response time: enable caching/CDN, or check for slow middleware, before crawlers or link-unfurlers start timing out.",
  sitemap: "Generate a sitemap.xml at your site root and reference it from robots.txt to help search engines discover your pages.",
  "security-headers": "Add Strict-Transport-Security, X-Content-Type-Options, X-Frame-Options, and Content-Security-Policy response headers at your server/CDN layer.",
  "og-image-alt": 'Add <meta property="og:image:alt" content="Description of the image"> for screen readers.',
  "twitter-image-alt": 'Add <meta name="twitter:image:alt" content="Description of the image"> for screen readers.',
  "article-tags": 'If this is an article, add article:published_time / article:modified_time meta tags for richer previews.',
  "twitter-creator": 'Add <meta name="twitter:creator" content="@authorhandle"> to credit the content author.',
  "author-present": 'Add <meta name="author" content="Your Name or Organization">.',
  "content-type-header": "Ensure your server sends a Content-Type response header (e.g. text/html; charset=utf-8).",
  "structured-data": 'Add a <script type="application/ld+json"> block describing the page (Article, Product, Organization, etc.) to improve rich results in search.',
  "duplicate-title-desc": "Rewrite the description so it adds new information instead of repeating the title verbatim.",
};
